/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snda_youni_patchtool_PatchUtil */

#ifndef _Included_com_snda_youni_patchtool_PatchUtil
#define _Included_com_snda_youni_patchtool_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snda_youni_patchtool_PatchUtil
 * Method:    applyPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_snda_youni_patchtool_PatchUtil_applyPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
